dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "8"
cache:
  yarn: true
env:
  -
  - SOLIDITY_COVERAGE=true
matrix:
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true
script:
  - ./scripts/ci.sh
before_deploy: npm run buildfornpm
deploy:
  provider: npm
  email: chadima.jiri@gmail.com
  skip_cleanup: true
  api_key: $NPM_TOKEN
  on:
    branch: master
    tags: true


